name: 🧪 Deploy to Development

on:
  push:
    branches: [ "develop", "feature/*" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  deployments: write

env:
  DOTNET_VERSION: '6.0.x'
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  ENVIRONMENT: development

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: 🔨 Build & Test
    outputs:
      version: ${{ steps.version.outputs.version }}
      
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Generate Version
      id: version
      run: |
        VERSION="dev-$(date +%Y%m%d)-$(git rev-parse --short HEAD)"
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "VERSION=$VERSION" >> $GITHUB_ENV
    
    - name: Restore dependencies
      run: dotnet restore TEZ_Project.Console.sln
    
    - name: Build
      run: dotnet build TEZ_Project.Console.sln --no-restore --configuration Debug
    
    - name: Run Tests
      run: dotnet test TEZ_Project.Console.sln --no-restore --collect "XPlat Code Coverage"
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-dev
        path: TestResults/

  docker-build:
    runs-on: ubuntu-latest
    name: 🐳 Docker Build
    needs: build-and-test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=raw,value=dev-latest
          type=raw,value=${{ needs.build-and-test.outputs.version }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy-dev:
    runs-on: ubuntu-latest
    name: 🚀 Deploy to Development
    needs: [build-and-test, docker-build]
    environment: 
      name: development
      url: https://dev.tez-project.dev
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Create deployment
      uses: actions/github-script@v7
      id: deployment
      with:
        script: |
          const deployment = await github.rest.repos.createDeployment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: context.sha,
            environment: 'development',
            auto_merge: false,
            required_contexts: []
          });
          
          return deployment.data.id;
    
    - name: Deploy to Development Environment
      run: |
        echo "🚀 Deploying to development environment..."
        echo "Version: ${{ needs.build-and-test.outputs.version }}"
        echo "Environment: development"
        echo "Image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.build-and-test.outputs.version }}"
        
        # Симуляція розгортання
        sleep 3
        
        # Перевірка health check
        echo "🔍 Health check..."
        sleep 2
        
        echo "✅ Development deployment completed successfully!"
        echo "🌐 Dev URL: https://dev.tez-project.dev"
    
    - name: Update deployment status
      uses: actions/github-script@v7
      if: always()
      with:
        script: |
          const deploymentId = ${{ steps.deployment.outputs.result }};
          const state = '${{ job.status }}' === 'success' ? 'success' : 'failure';
          
          await github.rest.repos.createDeploymentStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            deployment_id: deploymentId,
            state: state,
            environment_url: 'https://dev.tez-project.dev',
            description: state === 'success' ? 'Deployment successful' : 'Deployment failed'
          });

  integration-tests:
    runs-on: ubuntu-latest
    name: 🧪 Integration Tests
    needs: deploy-dev
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Wait for deployment
      run: |
        echo "⏳ Waiting for deployment to be ready..."
        sleep 30
    
    - name: Run Integration Tests
      run: |
        echo "🧪 Running integration tests against development environment..."
        echo "Environment URL: https://dev.tez-project.dev"
        
        # Симуляція інтеграційних тестів
        echo "✅ API health check: PASSED"
        echo "✅ Database connectivity: PASSED"
        echo "✅ Basic functionality: PASSED"
        echo "✅ All integration tests passed!"

  smoke-tests:
    runs-on: ubuntu-latest
    name: 💨 Smoke Tests
    needs: deploy-dev
    
    steps:
    - name: Run Smoke Tests
      run: |
        echo "💨 Running smoke tests..."
        echo "🔍 Testing critical paths..."
        
        # Симуляція smoke тестів
        echo "✅ Application startup: OK"
        echo "✅ Main features: OK"
        echo "✅ Error handling: OK"
        echo "✅ All smoke tests passed!"

  notify:
    runs-on: ubuntu-latest
    name: 📢 Notification
    needs: [deploy-dev, integration-tests, smoke-tests]
    if: always()
    
    steps:
    - name: Notify Team
      run: |
        echo "📢 Development Deployment Notification"
        echo "=================================="
        echo "Branch: ${{ github.ref_name }}"
        echo "Version: ${{ needs.build-and-test.outputs.version }}"
        echo "Status: ${{ job.status }}"
        echo "Environment: https://dev.tez-project.dev"
        
        if [[ "${{ needs.deploy-dev.result }}" == "success" ]]; then
          echo "✅ Deployment successful!"
        else
          echo "❌ Deployment failed!"
        fi
